class company{
    private int count, itemNo,rackSize;
    public company(int size){
        rackSize=size;
        count=0;
        itemNo=1;
    }
    public void generateMobile(){
        try{
            while(count==rackSize){
            wait();
            }
            count++;
            Thread.sleep(100);
            System.out.println("Mobile "+ itemNo+"Generated by "+);
            notify();
    } catch(Exception e){
        System.out.println(e.getMessage());
    }
    }
    public void wrapMobile(){

    }
}

public class InterThreadTester {
    
}
